set -ex
python3 /home/sheng/Diffusion/hadti_net/test_angular_sr.py \
--dataroot /home/sheng/Diffusion/data \
--name hadti_net \
--model hadti \
--epoch latest \
--net U3D \
--input_nc 8  \
--output_nc 6  \
--dataset_mode test \
--data_norm z_scoreV2 \
--serial_batches \
--batch_size 1 \
--bounding \
--patch_shape 64 \
--patch_overlap 32 \
--input_batch_sizes 8 \
--eval \
--num_threads 0 \
--num_test 20 \
--save_prediction 1 \
--gpu_ids 1